port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
tun:
  enable: true
dns:
 enable: true
 listen: :53
 enhanced-mode: redir-host
 hosts:
  '*.dev.nz': 127.0.0.1
 nameserver:
   - 61.139.2.69
   - 218.6.200.139
 fallback:
   - 1.1.1.1
